version: '3.8'

services:
  mongodb:
    image: mongo:5.0.3
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
    networks:
      - mongodb-net
    ports:
      - "27017:27017"  
  python-api:
    build: .
    container_name: python-api
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    networks:
      - mongodb-net
    ports:
      - "8000:8000"  

networks:
  mongodb-net:
    driver: bridge
